[logging]
level="info"

[network]
enabled_regions=["eu868"]

[postgresql]
dsn="postgres://chirpstack:chirpstack@postgres/chirpstack?sslmode=disable"
max_open_connections=25

[redis]
servers=["redis://redis:6379"]

[integration.mqtt]
enabled=true
server="tcp://mosquitto:1883"
json=true
client_id="chirpstack"

[api]
bind="0.0.0.0:8080"
secret="supersecret-minimum-16-characters"

[codec.js]
max_execution_time="100ms"

[codec.lua]
max_execution_time="100ms"
