[network]
enabled_regions=["eu868"]

[postgresql]
dsn="postgres://chirpstack:chirpstack@postgres/chirpstack?sslmode=disable"
max_open_connections=10

[redis]
servers=["redis://redis:6379"]

[integration.mqtt]
enabled=true
server="tcp://mosquitto:1883"
json=true

[api]
bind="0.0.0.0:8080"
secret="you-must-replace-this-with-a-secret"

[gateway]
ca_cert=""
ca_key=""
